
edge_path = "./data/edges.xlsx"
node_path = "./data/nodes.xlsx"
street_path = "./data/streets.xlsx"

mid_stream_path = "./data/midstream.xlsx"
up_stream_path = "./data/upstream.xlsx"

min_dis = 3  # 笛卡尔积距离小于这个值将被视为同一个点

foods_per_person = "1"  # 每个人需要多少单位的物资
